[registries]
Thanos_PublicPackages = { index = "sparse+https://pkgs.dev.azure.com/windowspartners/MsCoreUefi_Thanos/_packaging/Thanos_PublicPackages/Cargo/index/" }

[source.crates-io]
replace-with = "Thanos_PublicPackages"

[target.x86_64-unknown-uefi]
rustflags = [
    "-C", "link-arg=/base:0x0",
    "-C", "link-arg=/subsystem:efi_boot_service_driver",
]

[target.i686-unknown-uefi]
rustflags = [
    "-C", "link-arg=/base:0x0",
    "-C", "link-arg=/subsystem:efi_boot_service_driver",
]

[target.aarch64-unknown-uefi]
rustflags = [
    "-C", "link-arg=/base:0x0",
    "-C", "link-arg=/subsystem:efi_boot_service_driver",
]
